# Generated by Django 4.2.21 on 2025-09-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrate_bill', '0003_alter_bill_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Your Company Name', max_length=200)),
                ('address_line1', models.CharField(default='Address Line 1', max_length=200)),
                ('address_line2', models.CharField(blank=True, default='Address Line 2', max_length=200)),
                ('phone', models.CharField(default='+1234567890', max_length=20)),
                ('email', models.EmailField(default='example@email.com', max_length=254)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Business Information',
                'verbose_name_plural': 'Business Information',
            },
        ),
    ]
