# Generated by Django 4.2.11 on 2025-12-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrate_bill', '0004_businessinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billitem',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='billitem',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billitem',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
