# Generated by Django 4.2.11 on 2025-12-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrate_bill', '0005_billitem_cgst_amount_billitem_cgst_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='billitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
