# Generated by Django 4.2.11 on 2025-12-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrate_bill', '0006_billitem_batch_number_billitem_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformation',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
