# Generated by Django 4.2.11 on 2025-12-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrate_bill', '0008_bill_payment_date_bill_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
