# Generated by Django 4.2.11 on 2025-12-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrate_bill', '0009_businessinformation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformation',
            name='security_password',
            field=models.CharField(default='1234', max_length=50),
        ),
    ]
