# Generated by Django 4.2.11 on 2025-12-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrate_bill', '0010_businessinformation_security_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformation',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID for receiving payments (e.g. username@bank)', max_length=50),
        ),
    ]
