# Generated by Django 4.2.11 on 2025-12-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrate_bill', '0011_businessinformation_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformation',
            name='terms_and_conditions',
            field=models.TextField(default='1. Goods once sold will not be taken back or exchanged.\n2. All disputes are subject to jurisdiction only.'),
        ),
    ]
