# Generated by Django 4.2.11 on 2025-12-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrate_bill', '0013_activationkey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformation',
            name='backup_reminder_days',
            field=models.IntegerField(default=7, help_text='Recommend backup every N days'),
        ),
        migrations.AddField(
            model_name='businessinformation',
            name='last_backup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
