# Generated by Django 5.2.8 on 2026-01-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrate_bill', '0015_bill_paid_amount_bill_remaining_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='hsn_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='billitem',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billitem',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='billitem',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
