# Generated by Django 5.2.8 on 2026-01-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrate_bill', '0016_billitem_hsn_number_billitem_igst_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='extra_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sub_district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
