# Generated by Django 5.2.8 on 2026-01-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrate_bill', '0017_customer_city_customer_district_customer_extra_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformation',
            name='city',
            field=models.CharField(default='City', max_length=100),
        ),
        migrations.AddField(
            model_name='businessinformation',
            name='pincode',
            field=models.CharField(default='000000', max_length=20),
        ),
        migrations.AddField(
            model_name='businessinformation',
            name='state',
            field=models.CharField(default='State', max_length=100),
        ),
    ]
