# Generated by Django 5.2.8 on 2026-01-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrate_bill', '0018_businessinformation_city_businessinformation_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformation',
            name='district',
            field=models.CharField(default='District', max_length=100),
        ),
        migrations.AddField(
            model_name='businessinformation',
            name='sub_district',
            field=models.CharField(default='Taluka', max_length=100),
        ),
    ]
