# Generated by Django 5.2.8 on 2026-01-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genrate_bill", "0020_bill_place_of_supply_bill_supply_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="gst_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
