# Generated by Django 4.2.11 on 2026-01-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genrate_bill", "0021_customer_gst_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessinformation",
            name="pan_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="customer",
            name="drug_license_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="pan_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
