# Generated by Django 6.0.2 on 2026-02-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genrate_bill', '0023_remove_customer_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivationKey',
        ),
        migrations.RemoveField(
            model_name='businessinformation',
            name='activation_expiry_date',
        ),
    ]
