# Generated by Django 5.2.8 on 2026-01-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_batch_number_product_expiry_date_product_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='hsn_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
